### ISSUE TITLE
[Bug Report] Causing a annoying "Processing..." when launch Anki and open a Deck On Mac m1

### ISSUE THREAD

**Issue by LionChenA** [piazzatron/anki-smart-notes#31]
Test with and without the latest Smark-Notes and Anki. The annoying "Processing..." continues few minutes with Smark-Notes on while immediately into a Deck without it. In addition, opening settings of Anki and quitting seems to lead the same problem.

**Comment by piazzatron** [comment]
Hey @LionChenA, sorry you're facing this, that's super annoying & I'll get this fixed ASAP for you.

To help me figure out what's going on:

Please turn on `debug mode` in advanced, and then paste `smart-notes.log` into this thread.

If you're on Mac, that's in: `~/Library/Application Support/Anki2/Addons21/1531888719/`  
On windows: `%APPDATA%/Anki2/Addons21/1531888719/`  
More info here if you're having trouble finding it: [https://docs.ankiweb.net/files.html#file-locations](https://docs.ankiweb.net/files.html#file-locations)

**Comment by LionChenA** [comment]
Hi, @piazzatron, I encounter problems with the open debug mode, so I run Anki in my terminal. The output is shown below. It looks like there's a connection issue with the new features in the latest version of Smart Notes.
```
Anki starting...
Initial setup...
Preparing to run...
2024-09-19 18:38:54,109:INFO:aqt.mediasrv: Serving on http://127.0.0.1:64868
todo: windows paths in import screen
Cleaning up config
[]
[]
[]
Starting main loop...
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
conf key heatmap should be fetched with col.get_config(), and saved with col.set_config()
JS error :1 Uncaught ReferenceError: get_controller_info is not defined
2024-09-19 18:38:55.391 Anki[80498:1463930] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-19 18:38:55.391 Anki[80498:1463930] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
Qt warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=841.734,786.633 gbl=841.734,786.633 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-841.734,-786.633 last=-841.734,-786.633 Δ 841.734,786.633) : no target window
smart_notes/sentry.py: [ERROR] Error pinging server: Cannot connect to host anki-smart-notes-server-production.up.railway.app:443 ssl:default [Connect call failed ('35.213.168.149', 443)]
2024-09-19 18:40:11,273:ERROR:smart_notes: Error pinging server: Cannot connect to host anki-smart-notes-server-production.up.railway.app:443 ssl:default [Connect call failed ('35.213.168.149', 443)]
```
Bu the way, I'm in China and usually surfing internet with a VPN. It works in other places.

**Comment by LionChenA** [comment]
I open the debug mode of smart notes. The log shows the same thing.
[smart-notes.log](https://github.com/user-attachments/files/17057923/smart-notes.log)

**Comment by piazzatron** [comment]
This was really helpful, thanks. Looks like a couple things are going on:

- For some reason, your VPN situation is preventing you from connecting to the Anki server; however for some reason probably unique to the VPN situation, the connection doesn't immediately fail, it sits there and eventually times out. The default timeout in aiohttp is 5 minutes!

- All of the background ops were single threaded on a task queue because Anki thought that they were using a collection, so when the server ping sits there waiting to time out, that would also delay any further network requests to OpenAI, etc. Probably why you saw the progress bar.

Fixes:
- Lower timeout from 5m -> 10s for pings
- Tell Anki that these requests don't touch any collections, so they can be multithreaded.

Check out v2.1.5 when you have a chance and let me know if your situation is improved!

**Comment by LionChenA** [comment]
I'm really glad to hear there's an update! I upgraded it, and it definitely fixed my issue. Thanks for all your hard work—this plugin has saved me so much time!

**Comment by piazzatron** [comment]
Excellent, glad this solved the problem! If you're finding Smart Notes useful consider upgrading to a paid version some day ;)
